GB.Web/Controllers/A_OrderController.cs
using GB.Data.Dto;
using GB.Web.CustomAuthentication;
using GB.Web.Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GB.Web.Controllers
{
    //!  Mvc Controller A_OrderController. 
    /*!
       Klasa A_OrderController służy do przekierowania akcji Http na Api Controller oraz przekazania danych do wyświetlenia na widokach, zarządzania zamówieniami przez administratora.
    */
    [CustomAuthorize(Roles = "Administrator")]
    public class A_OrderController : Controller
    {
        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia listy wszystkich zamówień na widoku \A_Order\GetOrders, otrzymanych z warstwy Api.
        */
        [HttpGet]
        public ActionResult GetOrders()
        {
            var data = new ApiClient().GetData<List<OrderDto>>("api/a_order/GetAll");
            return View(data);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia listy zaległych zamówień na widoku \A_Order\GetOrdersWithPenalties, otrzymanych z warstwy Api.
        */
        [HttpGet]
        public ActionResult GetOrdersWithPenalties()
        {
            var data = new ApiClient().GetData<List<OrderDto>>("api/a_order/GetOrdersWithPenalties");
            return View(data);
        }

        //!  Akcja ActionResult typu HttpPost. 
        /*!
           Służy do przekazania informacji do warstwy Api o zamówieniu do zamknięcia z widoku \A_Order\Finish.
        */
        public ActionResult FinishOrder(int orderID)
        {
            var result = new ApiClient().PostData<int>("api/a_order/Post/FinishOrder", orderID);
            return RedirectToAction("Index");
        }
    }
}

GB.Web/Controllers/GameController.cs
using GB.Data.Dto;
using GB.Web.CustomAuthentication;
using GB.Web.Logic;
using GB.Web.Models;
using GB.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace GB.Web.Controllers
{

    //!  Mvc Controller GameController. 
    /*!
       Klasa GameController służy do przekierowania akcji Http na Api Controller oraz przekazania danych gier do wyświetlenia na widokach.
    */
    public class GameController : Controller
    {
        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia listy gier na widoku \Game\Index, otrzymanej z warstwy Api.
        */
        public ActionResult Index()
        {
            var data = new ApiClient().GetData<List<GameDto>>("api/game/GetAll");
            return View(data);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia formularza do dodania nowej gry na widoku \Game\Add.
        */
        [CustomAuthorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult Add()
        {
            CreateGame game = new CreateGame();

            return View(game);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia formularza do edytowania isniejącej gry na widoku \Game\Edit.
        */
        [CustomAuthorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult Edit(int gameID)
        {
            var data = new ApiClient().GetData<GameDto>("api/game/Get?gameID=" + gameID);
            if(data.Image == null)
                data.Image = new byte[] { };
            CreateGame game = new CreateGame() {
                ID = data.ID,
                AgeRatingID = data.AgeRating.ID,
                Description = data.Description,
                GamePlatformID = data.GamePlatform.ID,
                Name = data.Name,
                Price = data.Price,
                ProductionID = data.Production.ID,
                ReleaseDate = data.ReleaseDate,
                ImageBase64 = Convert.ToBase64String(data.Image)
            };

            return View(game);
        }

        //!  Akcja ActionResult typu HttpPost. 
        /*!
           Służy do przekazania danych z formularza do edytowania isniejącej gry na widoku \Game\Edit do warstwy Api.
        */
        [CustomAuthorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult Edit(CreateGame game)
        {
            if (ModelState.IsValid)
            {
               byte[] fileData = null;
                if (game.Image!= null)
                {
                    var img = game.Image;
                    
                    using (var binaryReader = new BinaryReader(img.InputStream))
                    {
                        fileData = binaryReader.ReadBytes(img.ContentLength);
                    }
                }

                var result = new ApiClient().PostData<CreateGameDto>("api/game/Post/Update", new CreateGameDto()
                {
                    ID = game.ID,
                    Name = game.Name,
                    ReleaseDate = game.ReleaseDate,
                    ProductionID = game.ProductionID,
                    GamePlatformID = game.GamePlatformID,
                    AgeRatingID = game.AgeRatingID,
                    Price = game.Price,
                    Description = game.Description,
                    GameGenres = game.GameGenres,
                    Image = fileData
                });
                return RedirectToAction("Index");
            }
            return View(game);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia danych wybranej gry na widoku \Game\ViewGame, otrzymanych z warstwy Api.
        */
        [AllowAnonymous]
        public ActionResult ViewGame(int gameID)
        {
            var data = new ApiClient().GetData<GameDto>("api/game/Get?gameID=" + gameID);
            ViewGameVM vm = new ViewGameVM();
            vm.CreateVM(data);
            return View(vm);
        }

        //!  Akcja ActionResult typu HttpPost. 
        /*!
           Służy do przekazania danych z formularza do dodania nowej gry na widoku \Game\Add do warstwy Api.
        */
        [CustomAuthorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult Add(CreateGame game)
        {
            if (ModelState.IsValid)
            {
                var img = game.Image;
                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(img.InputStream))
                {
                    fileData = binaryReader.ReadBytes(img.ContentLength);
                }

                var result = new ApiClient().PostData<CreateGameDto>("api/game/Post/Create", new CreateGameDto()
                {
                    Name = game.Name,
                    ReleaseDate = game.ReleaseDate,
                    ProductionID = game.ProductionID,
                    GamePlatformID = game.GamePlatformID,
                    AgeRatingID = game.AgeRatingID,
                    Price = game.Price,
                    Description = game.Description,
                    GameGenres = game.GameGenres,
                    Image = fileData
                });
                return RedirectToAction("Index");
            }

            return View(game);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do usunięcia wybranej gry.
        */
        [CustomAuthorize(Roles = "Administrator")]
        public ActionResult Remove(int id)
        {
            var result = new ApiClient().PostData<int>("api/game/Post/Remove", id);
            return RedirectToAction("Index");
        }
    }
}

GB.Web/Views/A_Order/GetOrders.cshtml
@model List<GB.Data.Dto.OrderDto>
@{
    ViewBag.Title = "Orders";
}

<div class="col-md-1"></div>
<div class="col-md-10 user-orders">
    <h2 class="title">All orders</h2>
    <h4 class="title">@Model.Count found.</h4>
    <table class="table table-responsive table-borderless">
        <thead>
            <tr>
                <th>ID</th>
                <th>User</th>
                <th>CreatedAt</th>
                <th>ExpiresAt</th>
                <th>Days left</th>
                <th>Penalty</th>
                <th>Total Price</th>
                <th>Total Price with Penalty</th>
                <th>Is Returned</th>
                <th>Game Copies</th>
                <th></th>

            </tr>
            @foreach (var order in Model)
            {
                <tr>
                    <td>@order.ID</td>
                    <td>@order.User.FirstName @order.User.LastName </td>
                    <td>@order.CreatedAt.ToShortDateString()</td>
                    <td>@order.ExpiresAt.ToShortDateString()</td>
                    <td>
                        @if (order.ExpiresAt >= DateTime.Now)
                        {
                            <span>@order.ExpiresAt.Subtract(order.CreatedAt).Days days</span>
                        }
                        else
                        {
                            <span>EXPIRED</span>
                        }
                    </td>
                    <td>
                        @if (order.ExpiresAt < DateTime.Now)
                        {
                            <span>@order.ExpiresAt.Subtract(order.CreatedAt).Days * 0.30</span>
                        }
                        else
                        {
                            <span></span>
                        }
                    </td>
                    <td>@order.TotalPrice</td>
                    <td>
                        @if (order.ExpiresAt < DateTime.Now)
                        {
                            <span>@order.TotalPrice+@order.ExpiresAt.Subtract(order.CreatedAt).Days * 0.30</span>
                        }
                        else
                        {
                            <span>@order.TotalPrice</span>
                        }
                    </td>
                    <td>
                        @if (order.IsFinishedAt != null)
                        {
                            <span>Yes</span>
                        }
                        else
                        {
                            <span>No</span>
                        }
                    </td>
                    <td>
                        @foreach (var orderGameCopy in order.OrderGameCopies)
                        {
                            <span><a href="@Url.Action("ViewGame", "Game", new { gameID = orderGameCopy.GameID})">@orderGameCopy.GameName</a>, @orderGameCopy.LocationName</span><br /><br />
                        }
                    </td>
                    <td>
                        <button class="btn btn-primary finish" data-slno="@order.ID" onclick="location.href='@Url.Action("FinishOrder","A_Order", new { orderID =  order.ID})'">
                            Finish Order
                        </button>
                    </td>
                </tr>
            }
        </thead>
    </table>
</div>
<div class="col-md-1"></div>

GB.Web/Views/A_Order/GetOrdersWithPenalties.cshtml
@model List<GB.Data.Dto.OrderDto>
@{
    ViewBag.Title = "Orders With Penalties";
}

<div class="col-md-1"></div>
<div class="col-md-10 user-orders">
    <h2 class="title">Orders with Penalties</h2>
    <h4 class="title">@Model.Count found.</h4>
    <table class="table table-responsive table-borderless">
        <thead>
            <tr>
                <th>ID</th>
                <th>User</th>
                <th>CreatedAt</th>
                <th>ExpiresAt</th>
                <th>Days left</th>
                <th>Penalty</th>
                <th>Total Price</th>
                <th>Total Price with Penalty</th>
                <th>Is Returned</th>
                <th>Game Copies</th>
                <th></th>

            </tr>
            @foreach (var order in Model)
            {
                <tr>
                    <td>@order.ID</td>
                    <td>@order.User.FirstName @order.User.LastName </td>
                    <td>@order.CreatedAt.ToShortDateString()</td>
                    <td>@order.ExpiresAt.ToShortDateString()</td>
                    <td>
                        @if (order.ExpiresAt >= DateTime.Now)
                        {
                            <span>@order.ExpiresAt.Subtract(order.CreatedAt).Days days</span>
                        }
                        else
                        {
                            <span>EXPIRED</span>
                        }
                    </td>
                    <td>
                        @if (order.ExpiresAt < DateTime.Now)
                        {
                            <span>@order.ExpiresAt.Subtract(order.CreatedAt).Days * 0.30</span>
                        }
                        else
                        {
                            <span></span>
                        }
                    </td>
                    <td>@order.TotalPrice</td>
                    <td>
                        @if (order.ExpiresAt < DateTime.Now)
                        {
                            <span>@order.TotalPrice+@order.ExpiresAt.Subtract(order.CreatedAt).Days * 0.30</span>
                        }
                        else
                        {
                            <span>@order.TotalPrice</span>
                        }
                    </td>
                    <td>
                        @if (order.IsFinishedAt != null)
                        {
                            <span>Yes</span>
                        }
                        else
                        {
                            <span>No</span>
                        }
                    </td>
                    <td>
                        @foreach (var orderGameCopy in order.OrderGameCopies)
                        {
                            <span><a href="@Url.Action("ViewGame", "Game", new { gameID = orderGameCopy.GameID})">@orderGameCopy.GameName</a>, @orderGameCopy.LocationName</span><br /><br />
                        }
                    </td>
                    <td>
                        <button class="btn btn-primary finish" data-slno="@order.ID" onclick="location.href='@Url.Action("FinishOrder","A_Order", new { orderID =  order.ID})'">
                            Finish Order
                        </button>
                    </td>
                </tr>
            }
        </thead>
    </table>
</div>
<div class="col-md-1"></div>