GB.Web/Controllers/GameController.cs
using GB.Data.Dto;
using GB.Web.CustomAuthentication;
using GB.Web.Logic;
using GB.Web.Models;
using GB.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace GB.Web.Controllers
{

    //!  Mvc Controller GameController. 
    /*!
       Klasa GameController służy do przekierowania akcji Http na Api Controller oraz przekazania danych gier do wyświetlenia na widokach.
    */
    public class GameController : Controller
    {
        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia listy gier na widoku \Game\Index, otrzymanej z warstwy Api.
        */
        public ActionResult Index()
        {
            var data = new ApiClient().GetData<List<GameDto>>("api/game/GetAll");
            return View(data);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia formularza do dodania nowej gry na widoku \Game\Add.
        */
        [CustomAuthorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult Add()
        {
            CreateGame game = new CreateGame();

            return View(game);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia formularza do edytowania isniejącej gry na widoku \Game\Edit.
        */
        [CustomAuthorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult Edit(int gameID)
        {
            var data = new ApiClient().GetData<GameDto>("api/game/Get?gameID=" + gameID);
            if(data.Image == null)
                data.Image = new byte[] { };
            CreateGame game = new CreateGame() {
                ID = data.ID,
                AgeRatingID = data.AgeRating.ID,
                Description = data.Description,
                GamePlatformID = data.GamePlatform.ID,
                Name = data.Name,
                Price = data.Price,
                ProductionID = data.Production.ID,
                ReleaseDate = data.ReleaseDate,
                ImageBase64 = Convert.ToBase64String(data.Image)
            };

            return View(game);
        }

        //!  Akcja ActionResult typu HttpPost. 
        /*!
           Służy do przekazania danych z formularza do edytowania isniejącej gry na widoku \Game\Edit do warstwy Api.
        */
        [CustomAuthorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult Edit(CreateGame game)
        {
            if (ModelState.IsValid)
            {
               byte[] fileData = null;
                if (game.Image!= null)
                {
                    var img = game.Image;
                    
                    using (var binaryReader = new BinaryReader(img.InputStream))
                    {
                        fileData = binaryReader.ReadBytes(img.ContentLength);
                    }
                }

                var result = new ApiClient().PostData<CreateGameDto>("api/game/Post/Update", new CreateGameDto()
                {
                    ID = game.ID,
                    Name = game.Name,
                    ReleaseDate = game.ReleaseDate,
                    ProductionID = game.ProductionID,
                    GamePlatformID = game.GamePlatformID,
                    AgeRatingID = game.AgeRatingID,
                    Price = game.Price,
                    Description = game.Description,
                    GameGenres = game.GameGenres,
                    Image = fileData
                });
                return RedirectToAction("Index");
            }
            return View(game);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia danych wybranej gry na widoku \Game\ViewGame, otrzymanych z warstwy Api.
        */
        [AllowAnonymous]
        public ActionResult ViewGame(int gameID)
        {
            var data = new ApiClient().GetData<GameDto>("api/game/Get?gameID=" + gameID);
            ViewGameVM vm = new ViewGameVM();
            vm.CreateVM(data);
            return View(vm);
        }

        //!  Akcja ActionResult typu HttpPost. 
        /*!
           Służy do przekazania danych z formularza do dodania nowej gry na widoku \Game\Add do warstwy Api.
        */
        [CustomAuthorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult Add(CreateGame game)
        {
            if (ModelState.IsValid)
            {
                var img = game.Image;
                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(img.InputStream))
                {
                    fileData = binaryReader.ReadBytes(img.ContentLength);
                }

                var result = new ApiClient().PostData<CreateGameDto>("api/game/Post/Create", new CreateGameDto()
                {
                    Name = game.Name,
                    ReleaseDate = game.ReleaseDate,
                    ProductionID = game.ProductionID,
                    GamePlatformID = game.GamePlatformID,
                    AgeRatingID = game.AgeRatingID,
                    Price = game.Price,
                    Description = game.Description,
                    GameGenres = game.GameGenres,
                    Image = fileData
                });
                return RedirectToAction("Index");
            }

            return View(game);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do usunięcia wybranej gry.
        */
        [CustomAuthorize(Roles = "Administrator")]
        public ActionResult Remove(int id)
        {
            var result = new ApiClient().PostData<int>("api/game/Post/Remove", id);
            return RedirectToAction("Index");
        }
    }
}

GB.Web/Controllers/OrderController.cs
using GB.Data.Dto;
using GB.Web.CustomAuthentication;
using GB.Web.Logic;
using GB.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GB.Web.Controllers
{
    //!  Mvc Controller OrderController. 
    /*!
       Klasa OrderController służy do przekierowania akcji Http na Api Controller oraz przekazania danych zamówień do wyświetlenia na widokach.
    */
    [CustomAuthorize(Roles = "Client")]
    public class OrderController : Controller
    {
        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia zawartości koszyka na widoku \Order\Checkout, otrzymanej z sesji użytkownika.
        */
        [HttpGet]
        public ActionResult Checkout()
        {
            NewOrderVM vm = new NewOrderVM();
            vm.OrderGameCopies = (List<AddToCartDto>)Session["cart"];
            vm.TotalPrice = vm.OrderGameCopies.Sum(x => x.Price);
            return View(vm);
        }

        //!  Akcja ActionResult typu HttpPost. 
        /*!
           Służy do przekazania informacji o zamówieniu do warstwy Api.
        */
        [HttpPost]
        public ActionResult Checkout(NewOrderVM vm)
        {
            CustomPrincipal user = HttpContext.User as CustomPrincipal;
            vm.UserID = user.UserID;
            if (ModelState.IsValid)
            {
                var result = new ApiClient().PostData<OrderDto>("api/order/Post/Create", new OrderDto()
                {
                    CreatedAt = DateTime.Now,
                    ExpiresAt = DateTime.Now.AddDays(14),
                    OrderGameCopies = vm.OrderGameCopies.Select(o => new OrderGameCopyDto {
                        GameID = o.GameID,
                        LocationID = o.LocationID
                    }).ToList(),
                    TotalPrice = vm.TotalPrice,
                    UserID = vm.UserID
                });
                return RedirectToAction("ClearCart", "Cart");
            }
            return View();
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia listy zamówień użytkownika na widoku \Order\ViewUserOrders, otrzymanej z warstwy Api.
        */
        [HttpGet]
        public ActionResult ViewUserOrders()
        {
            ViewOrdersVM vm = new ViewOrdersVM();
            CustomPrincipal user = HttpContext.User as CustomPrincipal;
            vm.Orders = new ApiClient().GetData<List<OrderDto>>("api/order/GetUserOrders?userID=" + user.UserID);
            return View(vm);
        }

        //!  Akcja ActionResult typu HttpGet. 
        /*!
           Służy do wyświetlenia danych wybranego zamówienia użytkownika na widoku \Order\Get, otrzymanych z warstwy Api.
        */
        [HttpGet]
        public ActionResult Get(int orderID)
        {
            OrderDto order = new ApiClient().GetData<OrderDto>("api/order/Get?orderID=" + orderID);
            return View(order);
        }
    }
}

GB.Web/Views/Order/Checkout.cshtml
@model GB.Web.ViewModels.NewOrderVM
@{
    ViewBag.Title = "Checkout Order";
}
<div class="col-md-1"></div>
<div class="col-md-10 user-cart">
    <h4 class="title">Please check your information carefully before submitting.</h4>
    @using (var form = Html.BeginForm("Checkout", "Order", FormMethod.Post))
    {
        for (int i = 0; i < Model.OrderGameCopies.Count(); i++)
        {
            @Html.HiddenFor(o => o.OrderGameCopies[i].GameID)
            @Html.HiddenFor(o => o.OrderGameCopies[i].LocationID)
        }
        @Html.HiddenFor(o => o.TotalPrice)
        <table class="table table-responsive table-borderless">
            <thead>
                <tr>
                    <th>Game Name</th>
                    <th>Location </th>
                    <th>Price</th>
                </tr>
                @foreach (var cartItem in Model.OrderGameCopies)
                {
                    <tr>
                        <td>@cartItem.GameName</td>
                        <td>@cartItem.LocationName</td>
                        <td>@cartItem.Price zł</td>
                    </tr>
                }
            </thead>
        </table>
        <h3 class="title">Total price: @Model.TotalPrice zł</h3>
        <button type="submit" class="btn btn-primary add">Submit Order</button>
    }
</div>
<div class="col-md-1"></div>
   

GB.Web/Views/Order/Get.cshtml
@model GB.Data.Dto.OrderDto
@{
    ViewBag.Title = "Order";
}

<div class="col-md-1"></div>
<div class="col-md-10 user-orders">
    <h2 class="title">Order nb. @Model.ID</h2>
    <div class="row">
        <div class="col-md-6">
            <h4 class="game-info-title">Created At: </h4><h5 class="game-info-item">@Model.CreatedAt.ToShortDateString()</h5>
            <h4 class="game-info-title">Expires In: </h4><h5 class="game-info-item">
                @if (Model.ExpiresAt >= DateTime.Now)
                {
                    <span>@Model.ExpiresAt.Subtract(DateTime.Now).Days days left</span>
                }
                else
                {
                    <span>EXPIRED</span>
                }
            </h5>
            <h4 class="game-info-title">Total Price: </h4><h5 class="game-info-item">@Model.TotalPrice</h5>
            <h4 class="game-info-title">Is Returned: </h4><h5 class="game-info-item">
                @if (Model.IsFinishedAt != null)
                {
                    <span>Yes</span>
                }
                else
                {
                    <span>No</span>
                }
            </h5>
        </div>
        <div class="col-md-6">
            <h3 class="title">Game Copies of Order:</h3>
            @foreach (var orderGameCopy in Model.OrderGameCopies)
            {
            <h5 class="game-info-item"><a href="@Url.Action("ViewGame", "Game", new { gameID = orderGameCopy.GameID})">@orderGameCopy.GameName</a>, @orderGameCopy.LocationName</h5><br /><br />
            }
        </div>
    </div>
</div>
<div class="col-md-1"></div>
   

GB.Web/Views/Order/ViewUserOrders.cshtml
@model GB.Web.ViewModels.ViewOrdersVM
@{
    ViewBag.Title = "My Orders";
}


<div class="col-md-1"></div>
<div class="col-md-10 user-orders">
    <h2 class="title">My Orders</h2>
    @if (Model.Orders.Count != 0)
    {
        <table class="table table-borderless table-responsive order-table">
            <thead>
                <tr>
                    <th>Order Number</th>
                    <th>Expires In</th>
                    <th>Is Returned</th>

                </tr>
                @foreach (var order in Model.Orders)
                {
                    <tr>
                        <td><a href="@Url.Action("Get", "Order", new { orderID = order.ID })">@order.ID</a></td>
                        <td>
                            @if (order.ExpiresAt >= DateTime.Now && @order.ExpiresAt.Subtract(DateTime.Now).Days != 1)
                            {
                                <span>@order.ExpiresAt.Subtract(DateTime.Now).Days days left</span>
                            }
                            else if (order.ExpiresAt >= DateTime.Now && @order.ExpiresAt.Subtract(DateTime.Now).Days == 1)
                            {
                                <span>@order.ExpiresAt.Subtract(DateTime.Now).Days day left</span>
                            }
                            else
                            {
                                <span>EXPIRED</span>
                            }
                        </td>
                        <td>
                            @if (order.IsFinishedAt != null)
                            {
                                <span>Yes</span>
                            }
                            else
                            {
                                <span>No</span>
                            }
                        </td>
                    </tr>
                }
            </thead>
        </table>

    }
    else
    {
        <h3>You don't have any orders yet. Go add some!</h3>
    }
</div>
<div class="col-md-1"></div>